### ISSUE TITLE
Issue Place Shoes Mask on Feet

### ISSUE THREAD

**Issue by honeykinng345** [PrinceP/congenial-system#2]
Can you please tell me what is happing with my code I am following your all steps and copying my model file into the asset box model.uuu file 
![WhatsApp Image 2022-08-31 at 17 41 52](https://user-images.githubusercontent.com/45269512/187680838-70ba61e1-7043-419a-bd54-6438c0a10a3b.jpeg)
here is my app showing me this result...

**Comment by PrinceP** [comment]
@honeykinng345  Can you give me the shoe model?

**Comment by honeykinng345** [comment]
> @honeykinng345 Can you give me the shoe model?

[box.obj.uuu.zip](https://github.com/PrinceP/congenial-system/files/9475024/box.obj.uuu.zip)
[model.obj.uuu.zip](https://github.com/PrinceP/congenial-system/files/9475025/model.obj.uuu.zip)

 please review the files that are uploaded. both files have the same code because of this command that you are mentioned
 (
#Animation file
cp mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetection3d/assets/sneaker/model.obj.uuu mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetection3d/assets/box.obj.uuu)

I just run the above command so the model.obj.uuu file that is inside the assets/ sneaker folder will copy into the asset/box.obj.uuu file

**Comment by PrinceP** [comment]
[assets.zip](https://github.com/PrinceP/congenial-system/files/9478845/assets.zip)

Can you use the following asset folder directly in 

mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetection3d

**Comment by honeykinng345** [comment]
> [assets.zip](https://github.com/PrinceP/congenial-system/files/9478845/assets.zip)
> 
> Can you use the following asset folder directly in
> 
> mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetection3d

@PrinceP Thanks bro now it's working ... can u please suggest to me how I can add more shoes mask?

**Comment by PrinceP** [comment]
Adding those features shortly in future.  
- Please add a star and follow this repository
- Be a [Sponsor](https://github.com/sponsors/PrinceP) for quicker updates.
